language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.3
    - android-26
  licenses:
    - '.+'
before_install:
    - yes | sdkmanager "platforms;android-26"
    - yes | sdkmanager "build-tools;27.0.3"
    
sudo: required
install: true

before_script:
  - chmod +x gradlew

script:
- ./gradlew assembleRelease --stacktrace
